# Development Dockerfile with hot reload
FROM python:3.11
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
ENV PYTHONUNBUFFERED=1
CMD ["/usr/local/bin/uvicorn","main:app","--host","0.0.0.0","--port","8000","--reload"]
